name: ardecorapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.11.0
  cloud_firestore: ^5.6.3
  firebase_auth: ^5.4.2
  firebase_storage: ^12.4.2
  fluttertoast: ^8.2.11
  model_viewer_plus: ^1.9.1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.3.3  # Added native splash package
  flutter_launcher_icons: ^0.14.3
flutter_icons:
  android:true
  ios:true
  image_path:"assets/logo.jpg"

flutter:
  uses-material-design: true
  assets:
    - assets/sillon.glb
    - assets/flower_arch.glb
    - assets/flower.glb
    - assets/white_arch.glb
    - assets/rock.glb
    - assets/signup_lines.png
    - assets/logo_gif.gif

flutter_native_splash:
  image: assets/logo_gif.gif  # Setting the splash screen GIF
  color: "#ffffff"        # Background color (change if needed)
  fullscreen: true        # Fullscreen splash screen
  android: true           # Enable splash for Android
  ios: true               # Enable splash for iOS